services:
  database:
    container_name: prefect-database
    image: postgres:17.0
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_DB=prefectapp
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
    volumes:
      - prefect_app_db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect -d prefectapp"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - prefect-django-app

  prefect:
    image: prefecthq/prefect:3.3.4.dev2-python3.12-conda
    container_name: prefect-server
    restart: always
    volumes:
      - prefect:/root/.prefect
    command: ["prefect", "server", "start"]
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_URL=http://localhost:4200
      - PREFECT_API_URL=http://localhost:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@database:5432/prefectapp
      - PREFECT_API_DATABASE_ECHO=False
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
    ports:
      - 4200:4200
    networks:
      - prefect-django-app
    depends_on:
      - database

  core:
    container_name: prefect-core
    build:
      context: django
      dockerfile: dockerfile
    user: 1000:1000
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ${HOME}/.vscode-server-prefect-core:/home/vscode/.vscode-server
    command: ./manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
      - prefect
    networks:
      - prefect-django-app
volumes:
  prefect_app_db:
    driver: local
  prefect:
    driver: local

networks:
  prefect-django-app:
